title: myblog
baseurl: "/myblog"
url: "https://sesseljabs.github.io"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "/myblog"
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: "/myblog"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/myblog"
    values:
      layout: "default"